
### Find all content
GET http://localhost:8080/api/content

### Get content by ID
GET http://localhost:8080/api/content/{{id}}

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "",
  "desc": "some kind of blogpost",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-10T12:09:38.057924",
  "dateUpdated": null,
  "url": ""

}


### Update a piece of Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "My FIRST Blog Post",
  "desc": "some kind of blogpost",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-10T12:09:38.057924",
  "dateUpdated": "2023-08-10T12:09:38.057924",
  "url": "http://localhost/firstblogpost"

}

### Update piece of content with invlaid ID
PUT http://localhost:8080/api/content/99
Content-Type: application/json

{
  "id": 1,
  "title": "My FIRST Blog Post",
  "desc": "some kind of blogpost",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-10T12:09:38.057924",
  "dateUpdated": "2023-08-10T12:09:38.057924",
  "url": "http://localhost/firstblogpost"

}

### Delete by ID
DELETE http://localhost:8080/api/content/2
